### ISSUE TITLE
Airdodge bug on nightly

### ISSUE THREAD

**Issue by NotSoAsian** [HDR-Development/HewDraw-Remix#668] opened 2022-06-11 04:48 UTC
On nightly, can infinitely airdodge in one instance airtime.

**Comment by WuBoytH** [comment] 2022-06-11 04:51
The issue is already fixed and will be in the next nightly.

**Closed as completed** 2022-06-11 04:51 UTC

**Comment by NotSoAsian** [comment] 2022-06-11 05:29
okay cool
