### ISSUE TITLE
Various Unexpected Behaviors of Held Buttons

### ISSUE THREAD

**Issue by JaiChong** [HDR-Development/HewDraw-Remix#2115] opened 2023-12-06 23:13 UTC
There are three issues regarding held-input logic that may need to be resolved in tandem, so I'm throwing them all into one issue thread.

The first two introduce unnecessary and likely unintended execution tests that don't exist in games with the same mechanics, and don't seem to add interesting depth that'd be appreciated.  The last removes an option.

<br>

### 1. Unintended held inputs (Shield) carrying across character states (affects Zair characters)
First was pointed out in [another issue](https://github.com/HDR-Development/HewDraw-Remix/issues/444) some time ago.  Holding a shield button while transitioning from a shielding state to another (e.g. by jumping OOS or shield dropping) does not forego the shield input for characters with a Zair, forcing users to lose frames ensuring they've released shield before inputting Attack if they wish to use a non-Zair aerial - an action often intended to come out ASAP, as it is usually one of the Zair character's few good options OOS.

There is an arg to be made that reintroducing this assistive mechanic makes it more difficult to input a jump oos or shield drop into immediate Zair, though as far as I'm aware such usage is pretty unsafe and likely niche; without a preceding air dodge (using one would require releasing Shield anyhow), I'd imagine most that do use Zair in neutral do so lower to the ground or spaced far horizontally.  This more likely Zair intent does not require an immediate input, and so prioritizing non-Zair aerials while Shield is held across a state transition should not disrupt the game plan of players that do use it more frequently.

<br>

### 2. Held inputs (LS) not carrying across character states (out of shield stun) as intended
Directions held with the left-stick before or during shield stun do not carry forward to after shield stun ends in some circumstances, e.g. holding Up before or during shield stun in preparation to punish with an Up-B OOS instead inputs a Parry OOS.

<br>

### 3. Held inputs (B) not changing logic for other inputs (Digital Shield cancelling MM Nspec) as expected
This one I cannot fully verify, but I believe held Mega Man Nspec cannot be cancelled with Shield if both the `Special-to-Parry` control scheme is used and a player's spring triggers are removed (i.e. Shield input is only digital, with no analog in-between).  It instead gives a parry input, and the charge is not saved to the point it was held.  I'm assuming this is due to the charge save condition only triggering for an analog Shield input, as my friends have mentioned the move cancels fine for them, but have not been able to test such myself to be sure that's where the issue lies.

**Comment by rgumintz** [comment] 2024-05-24 04:06
Not sure if this is related to the others / the right place for this, but if shield is held while airborne and taunt/footstool is pressed then it performs an airdodge. Frustrating with platform movement, particularly plat/shield-dropping. 

Potentially helpful to note that it can happen both 

- from a shield state: hold shield -> jump -> taunt (will airdodge), and 
- without entering shield: jump -> aerial + hold shield -> taunt (will airdodge).

**Comment by SuddyN** [comment] 2024-08-22 16:30
all 3 problems in the original post have been resolved by changes to input handling for shield, zair, and parry.

your additional comment is intended behavior -- pressing the shield lock button (second shield button, or special/taunt) while holding shield will trigger airdodge

**Closed as completed by SuddyN** 2024-08-22 16:30 UTC
Labels: engine
