### ISSUE TITLE
occasional desyncs from tech rolls

### ISSUE THREAD

**Issue by itsameyoyo** [HDR-Development/HewDraw-Remix#276] opened 2022-03-14 03:55 UTC
apologies in advance for not necessarily knowing how to format this, also sorry if this is already a topic that exists i looked through the pre-existing ones and didn't see any titles that lined up with this

so i've been playing hdr with some friends for a bit and the game seems to consistently desync and end the game on tech rolls.  we came to this conclusion after i had mentioned a tech roll on the game end, where we found out that on one switch ness didn't land the tech roll but on my switch ness did land it.  my hypothesis could be wrong but is there some sort of desync with how the hitstun animations are, so while the character might be at a good height to still tech roll while in other positions on other switches the opponent isn't able to tech roll.

**Comment by jdipalermo27** [comment] 2022-03-14 18:35
Are all 4 nro's initialized in arcopolis for both switches, you should be able to tech roll in all situations where you would need to floor tech?

**Comment by jdipalermo27** [comment] 2022-03-14 18:37
Also are you both using the same patch?

**Comment by itsameyoyo** [comment] 2022-03-14 19:48
we're all running the same version and as far as i know all three of us installed it the exact same way with the exact same files

**Comment by techyCoder81** [comment] 2022-03-15 11:46
This is very strange, but its likely caused by installed version differences i would assume. Compare your title screen versions.

**Comment by Riah321** [comment] 2022-06-17 11:41
Tbis issue has been addressed. Please close this issue :)

**Comment by O1yyy** [comment] 2023-02-04 22:24
old issue, should be closed

**Closed as completed** 2023-07-27 03:01 UTC
