### ISSUE TITLE
Doc cannot reverse his up-b out of shield

### ISSUE THREAD

**Issue by Scorpio3002** [HDR-Development/HewDraw-Remix#440] opened 2022-04-05 02:21 UTC
This has been a lingering issue, just want to document it here. It is impossible for Doc to reverse his up-b OOS; any attempt just winds up cancelling it.

**Comment by Riah321** [comment] 2022-06-17 11:38
This is intended behavior, but has been refined in the new beta. Please close this issue :)

**Closed as completed** 2022-07-13 15:31 UTC
