### ISSUE TITLE
Super happy tree cloud collisions active w/ hazards on

### ISSUE THREAD

**Issue by jobrien97** [HDR-Development/HewDraw-Remix#252] opened 2022-03-12 16:31 UTC
Either need to stdat edit them away or remove collisions from lvd.

**Comment by jdipalermo27** [comment] 2022-03-14 14:02
This is a duplicate of issue #230

**Comment by Riah321** [comment] 2022-06-17 11:58
Please close this issue as it is a duplicate and has been addressed.

**Closed as completed** 2023-07-27 03:04 UTC
Labels: bug, stages
